-- 코드를 입력하세요

SELECT B.PRODUCT_CODE PRODCUT_CODE, (A.SALES_AMOUNT * B.PRICE) SALES
FROM 
(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SALES_AMOUNT
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) A
JOIN (SELECT PRODUCT_ID, PRODUCT_CODE, PRICE
FROM PRODUCT) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC