SELECT CAR_ID, CAR_TYPE, FEE
FROM (
    SELECT CAR_ID, A.CAR_TYPE, CAST(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100 AS SIGNED INT) FEE
    FROM (
        (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE < '2022-11-30' AND END_DATE > '2022-11-01'
        )) A
        JOIN
        (
            SELECT CAR_TYPE, DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE DURATION_TYPE LIKE '30%'
        ) B
        ON A.CAR_TYPE = B.CAR_TYPE
    ) 
) C
WHERE FEE >= 500000 AND FEE < 2000000 AND (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV')
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC