-- 코드를 작성해주세요
WITH COLONY_RANK AS (
    SELECT ID, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) rnk
    FROM ECOLI_DATA
)

SELECT ID,
    CASE
        WHEN rnk / COUNT(*) OVER() <= 0.25 THEN "CRITICAL"
        WHEN rnk / COUNT(*) OVER() <= 0.5 THEN "HIGH"
        WHEN rnk / COUNT(*) OVER() <= 0.75 THEN "MEDIUM"
        ELSE "LOW"
    END AS COLONY_NAME
FROM COLONY_RANK
ORDER BY ID ASC