WITH SEOUL_REST AS (
    SELECT *
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
)

SELECT S.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(SUM(REVIEW_SCORE) / COUNT(S.REST_ID), 2) SCORE
FROM SEOUL_REST S JOIN REST_REVIEW R ON S.REST_ID = R.REST_ID
GROUP BY S.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC