-- 코드를 입력하세요

SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
EXCEPT
SELECT A.ANIMAL_ID ANIMAL_ID, A.NAME NAME
FROM
(SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS) A
INNER JOIN (SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS) B
ON A.ANIMAL_ID = B.ANIMAL_ID