SELECT O.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) * PRICE TOTAL_SALE
FROM FOOD_ORDER O
    JOIN FOOD_PRODUCT P
    ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALE DESC, O.PRODUCT_ID ASC
