SELECT F.FLAVOR
FROM FIRST_HALF F
    JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR) A
    ON F.FLAVOR = A.FLAVOR
ORDER BY F.TOTAL_ORDER + A.TOTAL_ORDER DESC
LIMIT 3