-- 코드를 입력하세요
WITH USED_GOODS_BOARD_DONE AS (
    SELECT *
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
)

SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD_DONE B
    JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC