WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_REVIEW_MEMBER AS (
    SELECT MEMBER_ID
    FROM REVIEW_COUNT
    WHERE REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT) FROM REVIEW_COUNT)
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MAX_REVIEW_MEMBER M
    JOIN MEMBER_PROFILE P ON M.MEMBER_ID = P.MEMBER_ID
    JOIN REST_REVIEW R ON R.MEMBER_ID = M.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC