WITH BEST_BOARD AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE F JOIN BEST_BOARD B ON F.BOARD_ID = B.BOARD_ID
ORDER BY FILE_ID DESC