-- 코드를 입력하세요

SELECT A.BOOK_ID BOOK_ID, B.AUTHOR_NAME AUTHOR_NAME, A.PUBLISHED_DATE PUBLISHED_DATE
FROM
(SELECT BOOK_ID, AUTHOR_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '경제') A
JOIN
AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC